In [3]:
#matrix
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=a+b
d=a-b
e=a*b
f=np.dot(a,b)
t=a.T
print("Addition")
print(c)
print("Substraction")
print(d)
print("Elementary multiplication")
print(e)
print("Matrix multiplication")
print(f)
print("Transpose")
print(t)


import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
U,S,VT=np.linalg.svd(X)
#choose no.of components
n_components=2
#reconstruct matrix
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("orginal matrix:")
print(X)
print("\n reconstructed matrix(with reduced diamensions):")
print(X_reconstructed)

Addition
[[ 6  8]
 [10 12]]
Substraction
[[-4 -4]
 [-4 -4]]
Elementary multiplication
[[ 5 12]
 [21 32]]
Matrix multiplication
[[19 22]
 [43 50]]
Transpose
[[1 3]
 [2 4]]
orginal matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 reconstructed matrix(with reduced diamensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
